// Code generated by protoc-gen-gin. DO NOT EDIT.

package user

import (
	gin "github.com/gin-gonic/gin"
	http "net/http"
)

type UserHttpServer struct {
	server UserServer
	router gin.IRouter
}

func RegisterUserServerHTTPServer(srv UserServer, r gin.IRouter) {
	s := UserHttpServer{
		server: srv,
		router: r,
	}
	s.RegisterService()
}

func (s *UserHttpServer) Register_0(c *gin.Context) {
	var in RegisterReq

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.Register(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) RegisterService() {

	s.router.Handle("POST", "", s.Register_0)

}
